name: 'Test'

on:
  push:
    paths-ignore:
      - '**.md'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22.x'
    - name: Install GNU Readline
      shell: bash
      run: sudo apt install -y libreadline-dev
    - name: Install libcurl
      shell: bash
      run: sudo apt install -y libcurl4-openssl-dev
    - name: Install raylib
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends libglfw3 libglfw3-dev libx11-dev libxcursor-dev libxrandr-dev libxinerama-dev libxi-dev libxext-dev libxfixes-dev libwayland-dev libxkbcommon-dev
        # Build raylib from source to avoid PPA issues
        git clone https://github.com/raysan5/raylib.git
        cd raylib
        mkdir build && cd build
        cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON ..
        make -j$(nproc)
        sudo make install
        sudo ldconfig
        cd ../..
    - name: Run and Show test results
      shell: bash
      run: make test
