name: 'Test'

on:
  push:
    paths-ignore:
      - '**.md'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22.x'
    - name: Install GNU Readline
      shell: bash
      run: sudo apt install -y libreadline-dev
    - name: Install libcurl
      shell: bash
      run: sudo apt install -y libcurl4-openssl-dev
    - name: Run and Show test results
      shell: bash
      run: make test
